/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef CHECK_PRIVATE_H
#define CHECK_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.24"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	24
#define COMPANY_NAME	"Lenovo"
#define FILE_VERSION	"1.0.0.24"
#define FILE_DESCRIPTION	"Control Process"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"1.0.0.24"

#endif /*CHECK_PRIVATE_H*/
