# Project: Projekt1
# Makefile created by Dev-C++ 5.2.0.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = BezNazwy1.o $(RES)
LINKOBJ  = BezNazwy1.o $(RES)
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc  
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" 
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" 
BIN      = Projekt1.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS   = $(INCS)  
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Projekt1.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Projekt1.exe" $(LIBS)

BezNazwy1.o: BezNazwy1.cpp
	$(CPP) -c BezNazwy1.cpp -o BezNazwy1.o $(CXXFLAGS)
