/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef SVCHOST_PRIVATE_H
#define SVCHOST_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.4"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	4
#define COMPANY_NAME	""
#define FILE_VERSION	"1.0.0.4"
#define FILE_DESCRIPTION	"svchost"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"1.0.0.4"

#endif /*SVCHOST_PRIVATE_H*/
